server:
  port: 8888

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    # url: jdbc:mysql://127.0.0.1:3306/db
    # username: zteroot
    # password: Superuser9!

    url: jdbc:sqlite:database.db
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never

    # url: jdbc:sqlite:database/mydatabase.db
    # driver-class-name: org.sqlite.JDBC
    # initialization-mode: never

#  jpa:
#    hibernate:
#      ddl-auto: none
#    database-platform: org.hibernate.dialect.SQLiteDialect
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLiteDialect


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
